;             red           green         blue
white       = (255 shl 0) + (255 shl 8) + (255 shl 16)
black       = (  0 shl 0) + (  0 shl 8) + (  0 shl 16)
grey        = (128 shl 0) + (128 shl 8) + (128 shl 16)
light_grey  = (180 shl 0) + (180 shl 8) + (180 shl 16)
dark_grey   = (60 shl 0) + (60 shl 8) + (60 shl 16)
gray        = grey
light_gray  = light_grey
dark_gray   = dark_grey
red         = (255 shl 0) + (  0 shl 8) + (  0 shl 16)
green       = (  0 shl 0) + (255 shl 8) + (  0 shl 16)
blue        = (  0 shl 0) + (  0 shl 8) + (255 shl 16)
yellow      = (255 shl 0) + (255 shl 8) + (  0 shl 16)
purple      = (255 shl 0) + (  0 shl 8) + (255 shl 16)
cyan        = (  0 shl 0) + (255 shl 8) + (255 shl 16)